name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: tag name
        id: tagName
        run: |
          TAG=${GITHUB_REF##*/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install oras

      - name: fetch and upload envoy (linux)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} linux amd64
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} linux arm64
          gh release upload ${{ steps.tagName.outputs.tag }} bin/envoy-linux-* --clobber

      - name: fetch and upload envoy (darwin)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} darwin amd64
          ./scripts/fetch-envoy ${{ steps.tagName.outputs.tag }} darwin arm64
          gh release upload ${{ steps.tagName.outputs.tag }} bin/envoy-darwin-* --clobber
